// Auto-generated by build-data.py. Do not edit by hand.
window.familyData = {
  "name": "Kanjirakkatt Thomman\n(Sankaran Namboodhiri)\n(Born 1735)",
  "col": "rootCol",
  "info": "Kanjirakkatt Sankaran Namboodhiri a.k.a. Kanjirakkatt Thomman (Born 1735)",
  "spouse": {
    "name": "Mariam Tharappel",
    "col": "femaleCol"
  },
  "children": [
    {
      "name": "Kochuthresia\n(1773)",
      "col": "femaleCol",
      "info": "Kochuthresia (Born 1773)",
      "spouse": null,
      "children": []
    },
    {
      "name": "Mariam\n(1776)",
      "col": "femaleCol",
      "info": "Mariam (Born 1776)",
      "spouse": null,
      "children": []
    },
    {
      "name": "Thomman\n(1780)",
      "col": "maleCol",
      "info": "Thomman (Born 1780)",
      "spouse": null,
      "children": [
        {
          "name": "Thomman\n(1833)",
          "col": "maleCol",
          "info": "Thomman (Born 1833)",
          "spouse": null,
          "children": [
            {
              "name": "Thomman\n(1869)",
              "col": "maleCol",
              "info": "Thomman Thomman (Came from Pala Vellappallil and lived at Elikulam)",
              "spouse": null,
              "children": [
                {
                  "name": "Thomas\n(1893)",
                  "col": "maleCol",
                  "info": "Thomas Thomman (Kunju) (Born:Feb-25-1893 Died:Sep-19-1981), Thachapuzha; Wife-Aleyamma - Madamattom-Naduthottiyil",
                  "spouse": {
                    "name": "Aleyamma",
                    "col": "femaleCol"
                  },
                  "children": [
                    {
                      "name": "Joseph",
                      "col": "maleCol",
                      "info": "Joseph Thomas, Kanjirakkattu, Thachapuzha; Wife-Mariamma - Thachapuzha-Kunnappallil",
                      "spouse": {
                        "name": "Mariamma",
                        "col": "femaleCol"
                      },
                      "children": [
                        {
                          "name": "Pappachan",
                          "col": "maleCol",
                          "info": "Late Pappachan (Thomas), Kanjirakkattu, Vechoochira; Wife-Leelamma - Vechoochira-Maniyangattu",
                          "spouse": {
                            "name": "Leelamma",
                            "col": "femaleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Sebastian",
                          "col": "maleCol",
                          "info": "Sebastian (Devasia), Kanjirakkattu, Vechoochira; Wife-Kuttiyamma - Vechoochira-Plavilaplackal",
                          "spouse": {
                            "name": "Kuttiyamma",
                            "col": "femaleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Jose",
                          "col": "maleCol",
                          "info": "Jose, Kanjirakkattu, Kannampally; Wife-Kunjoonjamma - Chunkappara-Vellikkarayil",
                          "spouse": {
                            "name": "Kunjoonjamma",
                            "col": "femaleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Mathew",
                          "col": "maleCol",
                          "info": "Mathew (Kuttiyachan), Kanjirakkattu, Kannampally; Wife-Salomy - Karikkattoor-Plakkattu",
                          "spouse": {
                            "name": "Kuttiyamma",
                            "col": "femaleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Molly",
                          "col": "femaleCol",
                          "info": "Molly, ; Married to Mathew - Koovappallil-Vadasseril",
                          "spouse": {
                            "name": "Mathew",
                            "col": "maleCol"
                          },
                          "children": []
                        }
                      ]
                    },
                    {
                      "name": "Mariamma",
                      "col": "femaleCol",
                      "info": "Mariamma; Married to Mathai Elikulam-Eattathottu",
                      "spouse": {
                        "name": "Mathai",
                        "col": "maleCol"
                      },
                      "children": [
                        {
                          "name": "Mathew",
                          "col": "maleCol",
                          "info": "Mathew (Kochu), Eattathottu, Paika; Wife-Theyyamma - Paika-Njandupara",
                          "spouse": {
                            "name": "Theyyamma",
                            "col": "femaleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Thomas",
                          "col": "maleCol",
                          "info": "Thomas (Thommachan), Eattathottu, Paika; Wife- - Melukavu-Kavukattu",
                          "spouse": {
                            "name": "",
                            "col": "femaleCol"
                          },
                          "children": []
                        }
                      ]
                    },
                    {
                      "name": "Aleykutty",
                      "col": "femaleCol",
                      "info": "Aleykutty; Married to Joseph Mathai Chamampathal-Oozhikattu; now living in Malabar",
                      "spouse": {
                        "name": "Joseph",
                        "col": "maleCol"
                      },
                      "children": [
                        {
                          "name": "Mathukutty",
                          "col": "maleCol",
                          "info": "",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Chinnamma",
                          "col": "femaleCol",
                          "info": "Chinnamma, Married to Kuriachan - Mattakkara-Kalappurackal",
                          "spouse": {
                            "name": "Kuriachan",
                            "col": "maleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Thomas",
                          "col": "maleCol",
                          "info": "Thomas",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Alice",
                          "col": "femaleCol",
                          "info": "Alice",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Jose",
                          "col": "maleCol",
                          "info": "Jose",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Thankachan",
                          "col": "maleCol",
                          "info": "Late Thankachan",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Kochurani",
                          "col": "maleCol",
                          "info": "Kochurani",
                          "spouse": null,
                          "children": []
                        }
                      ]
                    },
                    {
                      "name": "Annamma",
                      "col": "femaleCol",
                      "info": "Late Annamma; Married to Avirachan Paika-Pazheparambil",
                      "spouse": {
                        "name": "Avirachan",
                        "col": "maleCol"
                      },
                      "children": [
                        {
                          "name": "Kariachan",
                          "col": "maleCol",
                          "info": "Kariachan Pazheparambil; Wife:Molly Kalaketty-Choorapoikayil",
                          "spouse": {
                            "name": "Molly",
                            "col": "femaleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Annakutty",
                          "col": "femaleCol",
                          "info": "Annakutty; Married to Jose - Pala-Porunnolil",
                          "spouse": {
                            "name": "Jose",
                            "col": "maleCol"
                          },
                          "children": []
                        }
                      ]
                    },
                    {
                      "name": "Thomas\n(Chachan)\n(1934)",
                      "col": "maleCol",
                      "info": "Thomas Thomas (Born: Dec-12-1934) Living at Kanjirakkatt, Ranni\nWife: Aleykutty Kottadikunnel\n(Born: Aug-18-1935)",
                      "spouse": {
                        "name": "Aleykutty",
                        "col": "femaleCol"
                      },
                      "children": [
                        {
                          "name": "Thomas\n(1955)",
                          "col": "maleCol",
                          "info": "Thomas K.T. (Born: Nov-07-1955)",
                          "spouse": {
                            "name": "Celine",
                            "col": "maleCol"
                          },
                          "children": [
                            {
                              "name": "Deepak",
                              "col": "maleCol",
                              "info": "Deepak Thomas",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Emily",
                              "col": "femaleCol",
                              "info": "Emily Thomas",
                              "spouse": null,
                              "children": []
                            }
                          ]
                        },
                        {
                          "name": "Leelamma\n(1959)",
                          "col": "femaleCol",
                          "info": "Elsamma Thomas",
                          "spouse": {
                            "name": "Thomas",
                            "col": "maleCol"
                          },
                          "children": [
                            {
                              "name": "Christine",
                              "col": "maleCol",
                              "info": "Christine Thomas",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Justine",
                              "col": "maleCol",
                              "info": "Justine Thomas",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Nestine",
                              "col": "maleCol",
                              "info": "Nestine Thomas",
                              "spouse": null,
                              "children": []
                            }
                          ]
                        },
                        {
                          "name": "Marykutty\n(1962)",
                          "col": "femaleCol",
                          "info": "Merit Jose",
                          "spouse": {
                            "name": "Jose",
                            "col": "maleCol"
                          },
                          "children": [
                            {
                              "name": "Anupa",
                              "col": "femaleCol",
                              "info": "Anupa Jose",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Anuja",
                              "col": "femaleCol",
                              "info": "Anuja Jose",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Robin",
                              "col": "maleCol",
                              "info": "Robin Jose",
                              "spouse": null,
                              "children": []
                            }
                          ]
                        },
                        {
                          "name": "Lizy\n(1963)",
                          "col": "femaleCol",
                          "info": "Lizy Jose",
                          "spouse": {
                            "name": "Shaji",
                            "col": "maleCol"
                          },
                          "children": [
                            {
                              "name": "Arun",
                              "col": "maleCol",
                              "info": "Arun Jose",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Austin",
                              "col": "maleCol",
                              "info": "Austine Jose",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Tomin",
                              "col": "maleCol",
                              "info": "Tomin Jose",
                              "spouse": null,
                              "children": []
                            }
                          ]
                        },
                        {
                          "name": "Jacob\n(1965)",
                          "col": "maleCol",
                          "info": "Reji Thomas",
                          "spouse": {
                            "name": "Laly",
                            "col": "titansCol"
                          },
                          "children": [
                            {
                              "name": "Merin",
                              "col": "femaleCol",
                              "info": "Merin Jacob",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Mettin",
                              "col": "femaleCol",
                              "info": "Mettin Jacob",
                              "spouse": null,
                              "children": []
                            }
                          ]
                        },
                        {
                          "name": "Sherly\n(1968)",
                          "col": "femaleCol",
                          "info": "Sherly Shajan",
                          "spouse": {
                            "name": "Shajan",
                            "col": "maleCol"
                          },
                          "children": [
                            {
                              "name": "Tejas",
                              "col": "maleCol",
                              "info": "Tejas Shajan",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Jyothis",
                              "col": "maleCol",
                              "info": "Jyothis Shajan",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Josina",
                              "col": "femaleCol",
                              "info": "Josina Shajan",
                              "spouse": null,
                              "children": []
                            }
                          ]
                        },
                        {
                          "name": "Jojo\n(1969)",
                          "col": "maleCol",
                          "info": "Jojo Thomas",
                          "spouse": {
                            "name": "Shanty",
                            "col": "maleCol"
                          },
                          "children": [
                            {
                              "name": "Joshua",
                              "col": "maleCol",
                              "info": "Joshua Thomas",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Jacinta",
                              "col": "femaleCol",
                              "info": "Jacinta Thomas",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Jaslyn",
                              "col": "femaleCol",
                              "info": "Jaslyn Thomas",
                              "spouse": null,
                              "children": []
                            }
                          ]
                        },
                        {
                          "name": "Tessy\n(1971)",
                          "col": "femaleCol",
                          "info": "Tessy Sajosh",
                          "spouse": {
                            "name": "Sajosh",
                            "col": "maleCol"
                          },
                          "children": [
                            {
                              "name": "Anto",
                              "col": "maleCol",
                              "info": "Anto Sajosh",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Angelo",
                              "col": "maleCol",
                              "info": "",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Aleena",
                              "col": "femaleCol",
                              "info": "",
                              "spouse": null,
                              "children": []
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "name": "Antony",
                      "col": "maleCol",
                      "info": "Antony Thomas, Kanjirakkattu, Thachapuzha; Wife-Thresiamma - Cherualli-Madathanikunnel",
                      "spouse": {
                        "name": "Thresiamma",
                        "col": "femaleCol"
                      },
                      "children": [
                        {
                          "name": "Elsy",
                          "col": "femaleCol",
                          "info": "Elsy; Married to James - Manimala-Mannapparambil",
                          "spouse": {
                            "name": "James",
                            "col": "maleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Rosily",
                          "col": "femaleCol",
                          "info": "Rosily; Married to Philip - Konni-Mekkattu",
                          "spouse": {
                            "name": "Philip",
                            "col": "maleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Gracy",
                          "col": "femaleCol",
                          "info": "Gracy; Married to Benny - Koovappally-Vadasseril",
                          "spouse": {
                            "name": "Benny",
                            "col": "maleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Mercy",
                          "col": "femaleCol",
                          "info": "Mercy; Married to - Mattakkara",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Thomson",
                          "col": "maleCol",
                          "info": "Thomson (Kunjumon); Wife:Nyci",
                          "spouse": {
                            "name": "Nyci",
                            "col": "femaleCol"
                          },
                          "children": []
                        },
                        {
                          "name": "Lucy",
                          "col": "maleCol",
                          "info": "Lucy; Married to - Muttar",
                          "spouse": null,
                          "children": []
                        }
                      ]
                    }
                  ]
                },
                {
                  "name": "Mathai",
                  "col": "maleCol",
                  "info": "Thomman Mathai, Kanjirakkattu",
                  "spouse": null,
                  "children": [
                    {
                      "name": "Maammy",
                      "col": "femaleCol",
                      "info": "Maammy; Kalthotty",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Achamma",
                      "col": "femaleCol",
                      "info": "Achamma; Married to Pappachan - Poovarany-Ganapathiplackal",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Thomas",
                      "col": "maleCol",
                      "info": "Thomas (Thommachan) Elangulam",
                      "spouse": null,
                      "children": [
                        {
                          "name": "Annakkutty",
                          "col": "femaleCol",
                          "info": "Annakkutty",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Pappachan",
                          "col": "maleCol",
                          "info": "Pappachan",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Kuttappai",
                          "col": "maleCol",
                          "info": "Kuttappai",
                          "spouse": null,
                          "children": []
                        }
                      ]
                    },
                    {
                      "name": "Simon",
                      "col": "maleCol",
                      "info": "Simon (Appachan), Kanjirakkatt, Kannampally",
                      "spouse": null,
                      "children": [
                        {
                          "name": "Annakkutty",
                          "col": "femaleCol",
                          "info": "Annakkutty - Thovala",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Mathew",
                          "col": "maleCol",
                          "info": "Mathew (Kochu)",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "George",
                          "col": "maleCol",
                          "info": "George Kanjirakkatt, Kannampally",
                          "spouse": null,
                          "children": [
                            {
                              "name": "Joshy",
                              "col": "maleCol",
                              "info": "Joshy - Singapore",
                              "spouse": null,
                              "children": []
                            },
                            {
                              "name": "Asha",
                              "col": "femaleCol",
                              "info": "Asha",
                              "spouse": null,
                              "children": []
                            }
                          ]
                        },
                        {
                          "name": "Jose",
                          "col": "maleCol",
                          "info": "Jose; Wife: - from Mattakkara-Thundikarottu",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Fr Sunny",
                          "col": "maleCol",
                          "info": "Rev. Fr. Sunny - Nagaland",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Mary",
                          "col": "femaleCol",
                          "info": "Mary",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Tomy",
                          "col": "maleCol",
                          "info": "Tomy",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Elsamma",
                          "col": "femaleCol",
                          "info": "Elsamma",
                          "spouse": null,
                          "children": []
                        },
                        {
                          "name": "Shaji",
                          "col": "maleCol",
                          "info": "Shaji",
                          "spouse": null,
                          "children": []
                        }
                      ]
                    },
                    {
                      "name": "Annamma",
                      "col": "femaleCol",
                      "info": "Annamma; Married to - Elampalli-Vattakkuzhi",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Mathew",
                      "col": "maleCol",
                      "info": "Mathew (Kochu); Wife: Annamma - Vazhoor-Thoonkuzhiyil",
                      "spouse": {
                        "name": "Annamma",
                        "col": "femaleCol"
                      },
                      "children": []
                    }
                  ]
                },
                {
                  "name": "Mariamma",
                  "col": "femaleCol",
                  "info": "Mariamma (Maammy) - Married to Elangoi-Kumbalanickal family",
                  "spouse": null,
                  "children": []
                },
                {
                  "name": "Annamma",
                  "col": "femaleCol",
                  "info": "Annamma - Married to Pala-Kuzhuppalayil family",
                  "spouse": null,
                  "children": []
                },
                {
                  "name": "Aleyamma",
                  "col": "femaleCol",
                  "info": "Aleyamma (Kunjeli) - Married to Michael (Kunjoonj) Marutholil family",
                  "spouse": null,
                  "children": [
                    {
                      "name": "Fr Marutholil",
                      "col": "femaleCol",
                      "info": "Rev. Dr. Marutholil",
                      "spouse": null,
                      "children": []
                    }
                  ]
                },
                {
                  "name": "Joseph",
                  "col": "maleCol",
                  "info": "Thomman Joseph, Kanjirakkattu, Elikulam",
                  "spouse": null,
                  "children": [
                    {
                      "name": "Tom Jose",
                      "col": "maleCol",
                      "info": "Tom Jose, Angamaly",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Pappachan",
                      "col": "maleCol",
                      "info": "Pappachan - Elikulam",
                      "spouse": {
                        "name": "Lillykutty",
                        "col": "femaleCol"
                      },
                      "children": []
                    },
                    {
                      "name": "Mary",
                      "col": "femaleCol",
                      "info": "Mary",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "John",
                      "col": "maleCol",
                      "info": "John, Trivandrum",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Joy",
                      "col": "maleCol",
                      "info": "Joy, Aluva Federal Bank",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Pennu",
                      "col": "femaleCol",
                      "info": "Pennu",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Sunny",
                      "col": "maleCol",
                      "info": "Late Sunny",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Babu",
                      "col": "maleCol",
                      "info": "Babu, Kollam, Titanium Co.",
                      "spouse": null,
                      "children": []
                    }
                  ]
                },
                {
                  "name": "Rosamma",
                  "col": "femaleCol",
                  "info": "Rosamma - Married to Varkey Kanjiramattom-Paruvananickal family",
                  "spouse": {
                    "name": "Varkey",
                    "col": "maleCol"
                  },
                  "children": [
                    {
                      "name": "Thomas",
                      "col": "maleCol",
                      "info": "Thomas (Thomachan)",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Rosamma",
                      "col": "femaleCol",
                      "info": "Rosamma (Mathukutty)",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Fr Jose",
                      "col": "maleCol",
                      "info": "Rev. Fr. Jose",
                      "spouse": null,
                      "children": []
                    },
                    {
                      "name": "Sr Mary",
                      "col": "femaleCol",
                      "info": "Sr. Mary",
                      "spouse": null,
                      "children": []
                    }
                  ]
                },
                {
                  "name": "Brigitha",
                  "col": "femaleCol",
                  "info": "Brigitha - Married to Mathew Thachapuzha-Ettiyil family",
                  "spouse": {
                    "name": "Mathew",
                    "col": "maleCol"
                  },
                  "children": []
                }
              ]
            },
            {
              "name": "Kochu\n(1871)",
              "col": "maleCol",
              "info": "Kochu (Born 1871)",
              "spouse": null,
              "children": []
            },
            {
              "name": "Kunjappan\n(1873)",
              "col": "maleCol",
              "info": "Kunjappan (Born 1873)",
              "spouse": null,
              "children": []
            },
            {
              "name": "Chacko\n(1876)",
              "col": "maleCol",
              "info": "Chacko (Born 1876)",
              "spouse": null,
              "children": []
            },
            {
              "name": "Annamma\n(1878)",
              "col": "femaleCol",
              "info": "Annamma (Born 1878)",
              "spouse": null,
              "children": []
            },
            {
              "name": "Mariam\n(1882)",
              "col": "femaleCol",
              "info": "Mariam Kallarackal (Born 1882)",
              "spouse": null,
              "children": []
            },
            {
              "name": "Mathai\n(1884)",
              "col": "maleCol",
              "info": "Mathai (Born 1884)",
              "spouse": null,
              "children": []
            },
            {
              "name": "Thresiamma\n(1887)",
              "col": "femaleCol",
              "info": "Thresiamma (Born 1887)",
              "spouse": null,
              "children": []
            },
            {
              "name": "Chandi\n(1890)",
              "col": "maleCol",
              "info": "Chandi (Born 1890)",
              "spouse": null,
              "children": []
            }
          ]
        },
        {
          "name": "Mathai\n(1836)",
          "col": "maleCol",
          "info": "Mathai (Born 1836)",
          "spouse": null,
          "children": []
        },
        {
          "name": "Mariam\n(1839)",
          "col": "femaleCol",
          "info": "(Born 1839)",
          "spouse": null,
          "children": []
        },
        {
          "name": "Rosa\n(1841)",
          "col": "femaleCol",
          "info": "(Born 1841)",
          "spouse": null,
          "children": []
        },
        {
          "name": "Chandi\n(1843)",
          "col": "maleCol",
          "info": "Chandi (Born 1843)",
          "spouse": null,
          "children": []
        },
        {
          "name": "Annamma\n(1847)",
          "col": "femaleCol",
          "info": "Annamma (Born 1847)",
          "spouse": null,
          "children": []
        },
        {
          "name": "Chacko\n(1850)",
          "col": "maleCol",
          "info": "(Born 1850)",
          "spouse": null,
          "children": []
        }
      ]
    },
    {
      "name": "Mathai\n(1783)",
      "col": "maleCol",
      "info": "Mathai (Born 1783)",
      "spouse": null,
      "children": []
    }
  ]
};
